#: ----------------Fonts---------------------

Fonts {{{

#: git clone --depth 1 --branch release https://github.com/adobe-fonts/source-code-pro.git ~/.fonts/adobe-fonts/source-code-pro
#:fc-cache -f -v ~/.fonts/adobe-fonts/source-code-pro
#: or 
#: https://www.reddit.com/r/linux/comments/529oy3/what_is_your_favorite_terminal_font/
#: command in comments


font_family   Source Code Pro
font_size     12.0

}}}


#: ---------------------Cursor----------------------

Cursor customization {{{

cursor #B6D8F2

cursor_text_color #77DD77

cursor_shape beam

}}}


#:---------------------Scrollback------------------

Scrollback {{{

scrollback_lines 2000

}}}


#:-------------------Mouse------------------------

Mouse {{{

Url_color #0d4744

url_style single

detect_urls yes


}}}


#:----------------Performace Tuning-----------------

Performance tuning {{{

input_delay 3

repaint_delay 10

sync_to_monitor yes

}}}


#:----------------Window Layout -------------------

Window layout {{{

active_border_color #D1BDFF

inactive_border_color #E2CBF7

active_tab_foreground   #D4FAFA
active_tab_background   #EAEBFF

inactive_tab_foreground #FEBCC8
inactive_tab_background #D3EEFF

}}}


#-----------------Colour Scheme------------------

Color Scheme {{{

include themes.conf

forground #4FC978
background #A8A8A8

background_opacity 0.9

}}}


#:---------------Colour Table----------------

#:The colour table {{{

#:}}}
