#!/usr/bin/env bash


# Random Wallpaper
dirpapers='ls ~/.config/hypr/Wallpapers/*.jpg -1 | wc -l' &
paperseleted=$((1 + RANDOM % $dirpapers))
feh --bg-fill ~/.config/hypr/Wallpapers/$paperselected'.jpg' &
bash ~/.config/polybar/scripts/pywal.sh ~/.config/hypr/Wallpapers/$paperselected &

# Solid Wallpaper - Get on my level hoe
#feh --bg-fill ~/.config/hypr/Wallpapers/'13.jpg' &
#bash ~/.config/polybar/scripts/pywal.sh ~/.config/hypr/Wallpapers/'13.jpg' &


# Autostart
# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &
bsp-layout set tall &
pkill picom &
picom --experimental-backends &
polybar &

# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 &

# Window Information
bspc config border_width 2 &
bspc config window_gap 12 &

bspc config split_ratio 0.5 &
bspc config borderless-monocle true &
bspc config gapless_monocle true &

bspc config pointer_follows_monitor true &
bspc config focus_follows_pointer true &

# $HOME/.fehbg &
# Rules
bspc rule -a Vlc state=floating follow=on &

